app:
  build: .
  command: ["rails","server","-b","0.0.0.0","-p","3000"]
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.4
  ports:
    - "5432"
